package model

// LlmComment represents a code review comment generated by the LLM.
type LlmComment struct {
	Path           string  `json:"path"`
	Content        string  `json:"content"`
	Severity       string  `json:"severity,omitempty"`   // blocker | major | minor | nit (self-assessed)
	Confidence     float64 `json:"confidence,omitempty"` // 0.0-1.0 self-assessed likelihood the issue is real
	SuggestionCode string  `json:"suggestion_code,omitempty"`
	ExistingCode   string  `json:"existing_code,omitempty"`
	StartLine      int     `json:"start_line"`
	EndLine        int     `json:"end_line"`
	Thinking       string  `json:"thinking,omitempty"`
}

// CodeReviewResult holds raw LLM-generated review suggestion for a code segment.
type CodeReviewResult struct {
	RelevantFile      string `json:"relevant_file"`
	SuggestionContent string `json:"suggestion_content"`
	ExistingCode      string `json:"existing_code"`
	SuggestionCode    string `json:"suggestion_code"`
}
